In [1]:
!pip install tensorflow scikit-learn pandas numpy matplotlib

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [3]:
import warnings
warnings.filterwarnings("ignore")

# 1. Data Exploration and Preprocessing

In [4]:
# Load the dataset
df = pd.read_csv("Alphabets_data.csv")

In [5]:
df_info = df.info()
df_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [6]:
df_head = df.head()
df_head

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10

In [7]:
# Check for missing values
missing_values = df.isnull().sum()
missing_values

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [8]:
# Data Preprocessing
label_encoder = LabelEncoder()
label_encoder

LabelEncoder()

In [9]:
df["letter"] = label_encoder.fit_transform(df["letter"])
df["letter"]

0        19
1         8
2         3
3        13
4         6
         ..
19995     3
19996     2
19997    19
19998    18
19999     0
Name: letter, Length: 20000, dtype: int64

In [10]:
# Normalize the numerical features
scaler = MinMaxScaler()
scaler

MinMaxScaler()

In [11]:
X = scaler.fit_transform(df.drop(columns=["letter"]))  # Normalizing features
y = df["letter"]  # Target variable
X,y

(array([[0.13333333, 0.53333333, 0.2       , ..., 0.53333333, 0.        ,
         0.53333333],
        [0.33333333, 0.8       , 0.2       , ..., 0.53333333, 0.26666667,
         0.66666667],
        [0.26666667, 0.73333333, 0.4       , ..., 0.46666667, 0.2       ,
         0.6       ],
        ...,
        [0.4       , 0.6       , 0.4       , ..., 0.8       , 0.13333333,
         0.26666667],
        [0.13333333, 0.2       , 0.26666667, ..., 0.6       , 0.33333333,
         0.53333333],
        [0.26666667, 0.6       , 0.4       , ..., 0.46666667, 0.13333333,
         0.53333333]]),
 0        19
 1         8
 2         3
 3        13
 4         6
          ..
 19995     3
 19996     2
 19997    19
 19998    18
 19999     0
 Name: letter, Length: 20000, dtype: int64)

In [12]:
# Summary of data after preprocessing
df_summary = {
    "Total Samples": df.shape[0],
    "Total Features": df.shape[1] - 1,  # Excluding target variable
    "Total Classes": len(label_encoder.classes_)
}
df_summary

{'Total Samples': 20000, 'Total Features': 16, 'Total Classes': 26}

In [13]:
# Show processed data samples
processed_data_sample = pd.DataFrame(X, columns=df.columns[1:]).head()
processed_data_sample

xbox      ybox  width    height     onpix      xbar      ybar  \
0  0.133333  0.533333    0.2  0.333333  0.066667  0.533333  0.866667   
1  0.333333  0.800000    0.2  0.466667  0.133333  0.666667  0.333333   
2  0.266667  0.733333    0.4  0.533333  0.400000  0.666667  0.400000   
3  0.466667  0.733333    0.4  0.400000  0.200000  0.333333  0.600000   
4  0.133333  0.066667    0.2  0.066667  0.066667  0.533333  0.400000   

      x2bar     y2bar     xybar    x2ybar    xy2bar     xedge    xedgey  \
0  0.000000  0.400000  0.400000  0.666667  0.533333  0.000000  0.533333   
1  0.333333  0.266667  0.866667  0.200000  0.600000  0.133333  0.533333   
2  0.133333  0.400000  0.666667  0.200000  0.466667  0.200000  0.466667   
3  0.266667  0.400000  0.266667  0.266667  0.666667  0.400000  0.666667   
4  0.400000  0.400000  0.400000  0.333333  0.600000  0.066667  0.466667   

      yedge    yedgex  
0  0.000000  0.533333  
1  0.266667  0.666667  
2  0.200000  0.600000  
3  0.133333  0.533333  
4  0.333333  0.666667

# 2. Model Implementation

In [14]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [15]:
# Split dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test

(array([[0.26666667, 0.46666667, 0.33333333, ..., 0.53333333, 0.26666667,
         0.53333333],
        [0.26666667, 0.46666667, 0.4       , ..., 0.53333333, 0.26666667,
         0.46666667],
        [0.2       , 0.33333333, 0.26666667, ..., 0.6       , 0.13333333,
         0.4       ],
        ...,
        [0.2       , 0.26666667, 0.4       , ..., 0.46666667, 0.2       ,
         0.6       ],
        [0.2       , 0.53333333, 0.26666667, ..., 0.53333333, 0.06666667,
         0.46666667],
        [0.06666667, 0.2       , 0.13333333, ..., 0.46666667, 0.        ,
         0.46666667]]),
 array([[0.2       , 0.4       , 0.33333333, ..., 0.46666667, 0.46666667,
         0.4       ],
        [0.26666667, 0.73333333, 0.4       , ..., 0.73333333, 0.46666667,
         0.33333333],
        [0.2       , 0.26666667, 0.33333333, ..., 0.4       , 0.13333333,
         0.53333333],
        ...,
        [0.33333333, 0.66666667, 0.46666667, ..., 0.53333333, 0.26666667,
         0.53333333],
        [0.2

In [16]:
# Define a basic ANN model with one hidden layer
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Hidden Layer
    keras.layers.Dense(26, activation='softmax')  # Output Layer (26 classes for A-Z)
])
model

<Sequential name=sequential, built=True>

In [17]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [18]:
# Train the model
history = model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test), verbose=1)
history

Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1419 - loss: 3.1236 - val_accuracy: 0.4285 - val_loss: 2.4653
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.4695 - loss: 2.2701 - val_accuracy: 0.5415 - val_loss: 1.8724
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5676 - loss: 1.7823 - val_accuracy: 0.5947 - val_loss: 1.5873
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6101 - loss: 1.5320 - val_accuracy: 0.6467 - val_loss: 1.4162
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6482 - loss: 1.3962 - val_accuracy: 0.6625 - val_loss: 1.3122
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6726 - loss: 1.2863 - val_accuracy: 0.6815 - val_loss: 1.2265
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6841 - loss: 1.2248 - val_accuracy: 0.6982 - val_loss: 1.1737
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6953 - loss: 1.1848 - val_accuracy: 0.

In [19]:
# Make predictions on test set
y_pred_probs = model.predict(X_test)
y_pred_probs

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


array([[2.68562453e-05, 2.69417209e-03, 1.31170789e-03, ...,
        1.19606316e-01, 6.20040519e-05, 5.18862844e-01],
       [4.02253084e-02, 4.87382850e-03, 1.89617909e-02, ...,
        2.18498215e-01, 4.13732193e-02, 8.09922232e-04],
       [9.87847030e-01, 1.71516319e-06, 2.65383551e-06, ...,
        8.02316135e-05, 3.94525923e-09, 6.19815751e-07],
       ...,
       [1.11741771e-03, 2.54944985e-04, 9.34769772e-03, ...,
        3.56308883e-03, 7.13285033e-07, 3.64303414e-05],
       [1.34597672e-03, 2.92821229e-03, 1.80344650e-05, ...,
        2.94501446e-02, 7.05764174e-01, 7.37012655e-04],
       [9.04926219e-06, 7.22500431e-07, 7.06188002e-05, ...,
        5.73225804e-02, 7.85397887e-01, 1.61908451e-06]], dtype=float32)

In [20]:
y_pred = y_pred_probs.argmax(axis=1)
y_pred

array([25, 11,  0, ..., 16, 24, 24])

In [21]:
# Calculate accuracy on test set
test_accuracy = accuracy_score(y_test, y_pred)
test_accuracy

0.778

# Task 3: Hyperparameter Tuning

In [22]:
!pip install keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.6 MB/s eta 0:00:00


In [23]:
import keras_tuner as kt
from tensorflow import keras

In [25]:
# Define function to build ANN model with tunable hyperparameters
def build_model(hp):
    model = keras.Sequential()
    model.add(keras.layers.Dense(hp.Int('units_1', 32, 128, step=32),
                                 activation=hp.Choice('activation_1', ['relu', 'tanh']),
                                 input_shape=(X_train.shape[1],)))

    model.add(keras.layers.Dense(hp.Int('units_2', 32, 128, step=32),
                                 activation=hp.Choice('activation_2', ['relu', 'tanh'])))

    model.add(keras.layers.Dense(26, activation='softmax'))

    model.compile(optimizer=keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate', [0.001, 0.0005, 0.0001])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

In [26]:
# Initialize tuner with the correct function
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    executions_per_trial=1,
    directory='hyperparameter_tuning',
    project_name='alphabet_ann'
)
tuner

In [27]:
# Perform hyperparameter tuning
tuner.search(X_train, y_train, epochs=20, validation_data=(X_test, y_test))

Trial 8 Complete [00h 00m 31s]
val_accuracy: 0.7770000100135803

Best val_accuracy So Far: 0.8712499737739563
Total elapsed time: 00h 04m 11s

Search: Running Trial #9

Value             |Best Value So Far |Hyperparameter
64                |96                |units_1
relu              |relu              |activation_1
32                |64                |units_2
tanh              |tanh              |activation_2
0.001             |0.001             |learning_rate

Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1915 - loss: 2.9661 - val_accuracy: 0.5400 - val_loss: 1.8223
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5635 - loss: 1.6768 - val_accuracy: 0.6510 - val_loss: 1.3505
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6535 - loss: 1.2881 - val_accuracy: 0.6765 - val_loss: 1.1842
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6868 - loss: 1.1544 - val_accuracy: 0.6975 - val_loss: 1.0911
Epoch 5/20


KeyboardInterrupt: 

In [28]:
# Retrieve the best hyperparameters
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
best_hps

In [29]:
# Train the final model with the best hyperparameters
best_model = tuner.hypermodel.build(best_hps)
best_model

<Sequential name=sequential_1, built=True>

In [30]:
history = best_model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test))
history

Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2728 - loss: 2.7453 - val_accuracy: 0.6192 - val_loss: 1.4856
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6337 - loss: 1.3704 - val_accuracy: 0.6860 - val_loss: 1.1501
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7031 - loss: 1.0999 - val_accuracy: 0.7380 - val_loss: 1.0101
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7315 - loss: 0.9827 - val_accuracy: 0.7300 - val_loss: 0.9362
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7441 - loss: 0.9130 - val_accuracy: 0.7548 - val_loss: 0.8741
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7600 - loss: 0.8417 - val_accuracy: 0.7602 - val_loss: 0.8327
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7746 - loss: 0.7938 - val_accuracy: 0.7915 - val_loss: 0.7508
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7880 - loss: 0.7500 - val_accuracy: 0.

In [31]:
# Evaluate the final tuned model
test_loss, test_accuracy = best_model.evaluate(X_test, y_test)
test_loss, test_accuracy

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8663 - loss: 0.4398


(0.4394700229167938, 0.871999979019165)

# 4. Evaluation

In [32]:
# Evaluate the default ANN model
y_pred_default = model.predict(X_test).argmax(axis=1)
accuracy_default = accuracy_score(y_test, y_pred_default)
precision_default = precision_score(y_test, y_pred_default, average='weighted')
recall_default = recall_score(y_test, y_pred_default, average='weighted')
f1_default = f1_score(y_test, y_pred_default, average='weighted')

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


In [33]:
# Evaluate the tuned ANN model
y_pred_tuned = best_model.predict(X_test).argmax(axis=1)
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
precision_tuned = precision_score(y_test, y_pred_tuned, average='weighted')
recall_tuned = recall_score(y_test, y_pred_tuned, average='weighted')
f1_tuned = f1_score(y_test, y_pred_tuned, average='weighted')

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [34]:
# Create a comparison dictionary
evaluation_results = {
    "Metric": ["Accuracy", "Precision", "Recall", "F1-Score"],
    "Default Model": [accuracy_default, precision_default, recall_default, f1_default],
    "Tuned Model": [accuracy_tuned, precision_tuned, recall_tuned, f1_tuned]
}

In [35]:
# Convert to DataFrame for better visualization
evaluation_df = pd.DataFrame(evaluation_results)
print(evaluation_df)

      Metric  Default Model  Tuned Model
0   Accuracy       0.778000     0.872000
1  Precision       0.782245     0.877525
2     Recall       0.778000     0.872000
3   F1-Score       0.775844     0.872664
